/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBuildingsRouteImport } from './routes/_authenticated/buildings'
import { Route as AuthenticatedBuyRouteImport } from './routes/_authenticated/buy'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedPassportRouteImport } from './routes/_authenticated/passport'
import { Route as AuthenticatedProcurementRouteImport } from './routes/_authenticated/procurement'
import { Route as AuthenticatedScenariosRouteImport } from './routes/_authenticated/scenarios'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBuildingsRoute = AuthenticatedBuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuyRoute = AuthenticatedBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPassportRoute = AuthenticatedPassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProcurementRoute =
  AuthenticatedProcurementRouteImport.update({
    id: '/procurement',
    path: '/procurement',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScenariosRoute = AuthenticatedScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/buildings': typeof AuthenticatedBuildingsRoute
  '/buy': typeof AuthenticatedBuyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/home': typeof AuthenticatedHomeRoute
  '/passport': typeof AuthenticatedPassportRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/scenarios': typeof AuthenticatedScenariosRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/buildings': typeof AuthenticatedBuildingsRoute
  '/buy': typeof AuthenticatedBuyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/home': typeof AuthenticatedHomeRoute
  '/passport': typeof AuthenticatedPassportRoute
  '/procurement': typeof AuthenticatedProcurementRoute
  '/scenarios': typeof AuthenticatedScenariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/buildings': typeof AuthenticatedBuildingsRoute
  '/_authenticated/buy': typeof AuthenticatedBuyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/passport': typeof AuthenticatedPassportRoute
  '/_authenticated/procurement': typeof AuthenticatedProcurementRoute
  '/_authenticated/scenarios': typeof AuthenticatedScenariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buildings'
    | '/buy'
    | '/dashboard'
    | '/home'
    | '/passport'
    | '/procurement'
    | '/scenarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buildings'
    | '/buy'
    | '/dashboard'
    | '/home'
    | '/passport'
    | '/procurement'
    | '/scenarios'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/buildings'
    | '/_authenticated/buy'
    | '/_authenticated/dashboard'
    | '/_authenticated/home'
    | '/_authenticated/passport'
    | '/_authenticated/procurement'
    | '/_authenticated/scenarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/buildings': {
      id: '/_authenticated/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof AuthenticatedBuildingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buy': {
      id: '/_authenticated/buy'
      path: '/buy'
      fullPath: '/buy'
      preLoaderRoute: typeof AuthenticatedBuyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passport': {
      id: '/_authenticated/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof AuthenticatedPassportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/procurement': {
      id: '/_authenticated/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof AuthenticatedProcurementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scenarios': {
      id: '/_authenticated/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof AuthenticatedScenariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBuildingsRoute: typeof AuthenticatedBuildingsRoute
  AuthenticatedBuyRoute: typeof AuthenticatedBuyRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPassportRoute: typeof AuthenticatedPassportRoute
  AuthenticatedProcurementRoute: typeof AuthenticatedProcurementRoute
  AuthenticatedScenariosRoute: typeof AuthenticatedScenariosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBuildingsRoute: AuthenticatedBuildingsRoute,
  AuthenticatedBuyRoute: AuthenticatedBuyRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPassportRoute: AuthenticatedPassportRoute,
  AuthenticatedProcurementRoute: AuthenticatedProcurementRoute,
  AuthenticatedScenariosRoute: AuthenticatedScenariosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
